# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:9.11.1

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - yarn global add truffle
          - yarn global add ganache-cli
          - yarn add run-with-testrpc
          - ./node_modules/.bin/run-with-testrpc --port 8545 'truffle test'
    - step:
        name: Compile contracts
        trigger: manual
        script:
          - truffle compile --reset --all
    - step:
        name: Build
        trigger: manual
        script:
          - yarn run build
          
      

